// Generated by gencpp from file matching_algorithm/Data1d.msg
// DO NOT EDIT!


#ifndef MATCHING_ALGORITHM_MESSAGE_DATA1D_H
#define MATCHING_ALGORITHM_MESSAGE_DATA1D_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace matching_algorithm
{
template <class ContainerAllocator>
struct Data1d_
{
  typedef Data1d_<ContainerAllocator> Type;

  Data1d_()
    : data()  {
    }
  Data1d_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::matching_algorithm::Data1d_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::matching_algorithm::Data1d_<ContainerAllocator> const> ConstPtr;

}; // struct Data1d_

typedef ::matching_algorithm::Data1d_<std::allocator<void> > Data1d;

typedef boost::shared_ptr< ::matching_algorithm::Data1d > Data1dPtr;
typedef boost::shared_ptr< ::matching_algorithm::Data1d const> Data1dConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::matching_algorithm::Data1d_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::matching_algorithm::Data1d_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace matching_algorithm

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': False, 'HasHeader': False}
// {'matching_algorithm': ['/home/intelpro/catkin_ws/src/matching_algorithm/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::matching_algorithm::Data1d_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::matching_algorithm::Data1d_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::matching_algorithm::Data1d_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::matching_algorithm::Data1d_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::matching_algorithm::Data1d_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::matching_algorithm::Data1d_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::matching_algorithm::Data1d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "788898178a3da2c3718461eecda8f714";
  }

  static const char* value(const ::matching_algorithm::Data1d_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x788898178a3da2c3ULL;
  static const uint64_t static_value2 = 0x718461eecda8f714ULL;
};

template<class ContainerAllocator>
struct DataType< ::matching_algorithm::Data1d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "matching_algorithm/Data1d";
  }

  static const char* value(const ::matching_algorithm::Data1d_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::matching_algorithm::Data1d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] data\n\
\n\
";
  }

  static const char* value(const ::matching_algorithm::Data1d_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::matching_algorithm::Data1d_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Data1d_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::matching_algorithm::Data1d_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::matching_algorithm::Data1d_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MATCHING_ALGORITHM_MESSAGE_DATA1D_H
